### ISSUE TITLE
please fix this problem google api.. this option not enable

### ISSUE THREAD

**Issue by rafiislambd** [Pjumpod/TumTop_download#1]
![1](https://github.com/user-attachments/assets/915a79a0-cf50-4c4c-a761-749977ab0d1b)

**Comment by Pjumpod** [comment]
This check needs to key in the User secret key first.

**Comment by rafiislambd** [comment]
> This check needs to key in the User secret key first.

where find secret key?

**Comment by Pjumpod** [comment]
> > This check needs to key in the User secret key first.
> 
> where find secret key?

you can scan the QR by the line application.
