### ISSUE TITLE
Install in MBA M2

### ISSUE THREAD

**Issue by zeuscs09** [Pjumpod/TumTop_download#3]
![image](https://github.com/user-attachments/assets/e5fce4da-d447-4715-9822-629e99e2c9ca)
Installation Error

**Comment by Pjumpod** [comment]
The message just said, "Apple does not know the developer". It does not show any error.

You can bypass this prompt by many way.

Read this => https://www.macworld.com/article/672947/how-to-open-a-mac-app-from-an-unidentified-developer.html
